### ISSUE TITLE
"Bad argument" error

### ISSUE THREAD

**Issue by crcastle** [heroku/heroku-container-registry#14]
I am getting a "Bad argument" error running `heroku container:login` and `heroku container:push`.  See below for version information and repro steps.

![image](https://cloud.githubusercontent.com/assets/275734/26026014/6e3aee5c-37eb-11e7-8e75-99e14cfe041b.png)

cc @dickeyxxx

**Comment by jdx** [comment]
@crcastle pushed out https://github.com/heroku/heroku-container-registry/commit/baeb6e84944d2e87d0102505267adc31d1ac3cb3 which should have a fix

**Comment by crcastle** [comment]
Thanks @dickeyxxx! Got past that but hit another issue https://github.com/heroku/heroku-container-registry/issues/15
