### ISSUE TITLE
Sanbashi is not defined

### ISSUE THREAD

**Issue by bromanko** [heroku/heroku-container-registry#19]
Today I installed the Heroku CLI from Homebrew (v6.12.6) on MacOS. I then installed the heroku-container-registry plugin. The login command fails with the following error:

```
$ heroku container:login
 ▸    Error: docker login exited with ReferenceError: Sanbashi is not defined
```

On another machine running Heroku CLI v6.7.4 I am not seeing this issue.

**Comment by bromanko** [comment]
Actually, this might be related to v4.2.1 which was just released an hour ago. I was able to install the previous version of this plugin (4.1.3) and login is working.

**Comment by jdx** [comment]
Can you update and try again?

**Comment by bromanko** [comment]
Looks good now. Thanks!
