### ISSUE TITLE
Expected response to be successful, got 422

### ISSUE THREAD

**Issue by jfloff** [heroku/heroku-container-registry#3]
I was redirected here from [heroku/cli](https://github.com/heroku/cli/issues/190). 

I'm trying to perform a container release but I keep getting 422 error message. I've tracked it down to the add-ons I'm choosing. I can deploy with only `heroku-postgresql` but as soon as I add some of my other addons (logentries, newrelic, rollbar, scheduler, sendgrid) it returns a 422.

Here's the log with `HEROKU_DEBUG=1`:

``` shell
heroku-cli/5.2.24-4b7e305 (darwin-amd64) go1.6.2 /Users/jfloff/.local/share/heroku/cli/bin/heroku cmd: version
heroku-cli/5.2.24-4b7e305 (darwin-amd64) go1.6.2 /Users/jfloff/.local/share/heroku/cli/bin/heroku cmd: commands
heroku-cli/5.2.24-4b7e305 (darwin-amd64) go1.6.2 /Users/jfloff/.local/share/heroku/cli/bin/heroku cmd: container:release
Remote addons: heroku-postgresql (1)
Local addons: heroku-postgresql:hobby-dev, logentries:le_tryit, newrelic:wayne, rollbar:free, scheduler:standard, sendgrid:starter (6)
Missing addons: logentries:le_tryit, newrelic:wayne, rollbar:free, scheduler:standard, sendgrid:starter (5)
Provisioning logentries:le_tryit...
Provisioning newrelic:wayne...
Provisioning rollbar:free...
Provisioning scheduler:standard...
Provisioning sendgrid:starter...
```

**Comment by dmathieu** [comment]
Hey there,

Is your account [verified](https://devcenter.heroku.com/articles/account-verification)? Unverified accounts can only provision the postgresql add-on.

As another note, the `container:release` command is deprecated. As a replacement, we released our [docker registry](https://devcenter.heroku.com/articles/container-registry-and-runtime) in public beta a couple weeks ago.
