### ISSUE TITLE
heroku container:login  ERROR !

### ISSUE THREAD

**Issue by refactormyself** [heroku/heroku-container-registry#4]
I am trying out the container registry following the getting started tutorial here - https://devcenter.heroku.com/articles/container-registry-and-runtime

heroku container:login gives error, it seems to be looking for the docker registry on localhost instead of registry.heroku.com (I guess). See snap shot :
![heroku-docker registry error](https://cloud.githubusercontent.com/assets/17991837/18059537/b09a63fa-6e19-11e6-8ac7-493b29870f3b.PNG)

I have also tried to use docker to login to the registry with my heroku account detail also no luck. 
I am using a windows 8.1 machine and it is the same result on cmd

**Comment by dmathieu** [comment]
Hey there,

This looks like a corporate firewall blocking port 2375. Could you try logging from another connection?
