### ISSUE TITLE
files attribute missing from package.json

### ISSUE THREAD

**Issue by rj919** [heroku/heroku-container-registry#69]
Just installed / upgrade the heroku container registry plugin.
heroku plugins:install @ heroku-cli/plugin-container-registry

System:
GalliumOS (Debian)
nvm virtual package manager for npm

Then ran:
heroku --version

Error Message:
(node:16573) Error Plugin: heroku-container-registry: files attribute must be specified in /home/rcj1492/.local/share/heroku/node_modules/heroku-container-registry/package.json
module: @oclif/config@1.6.27
plugin: heroku-container-registry
root: /home/rcj1492/.local/share/heroku/node_modules/heroku-container-registry
See more details with DEBUG=*
(node:16573) Error Plugin: heroku-container-registry: files attribute must be specified in /home/rcj1492/.local/share/heroku/node_modules/heroku-container-registry/package.json
module: @oclif/plugin-legacy@1.0.15
plugin: heroku-container-registry
root: /home/rcj1492/.local/share/heroku/node_modules/heroku-container-registry
See more details with DEBUG=*
heroku/7.0.85 linux-x64 node-v8.9.1

Workaround:
I added "files": [] to package.json and error goes away.

**Comment by dmathieu** [comment]
the [files attribute](https://github.com/heroku/heroku-container-registry/blob/master/package.json#L26) is in package.json.

@heroku/cli any idea where this could be coming from?

**Comment by jdx** [comment]
This plugin shouldn't be installed, it's already in the core CLI. `heroku-container-registry` is the old name for this plugin and is outdated. I added this plugin to the blacklist so it will be removed automatically on the next update.
