### ISSUE TITLE
State changed from starting to crashed

### ISSUE THREAD

**Issue by rj919** [heroku/heroku-container-registry#70]
Since the container:release process was introduced, I have been unable to find a way to get my docker containers (which previously deployed without a problem) to work. No matter what I try, after the push and release process completes without a problem on the command line, I always only get the following error message in the dashboard:

```State changed from starting to crashed```

I have tried to push multiple different apps (all in docker containers) and in each case, the docker containers startup (and run) without errors on my machine. And, prior to the new system being introduced, I did not experience any problem deploying the same apps to heroku. So, at this point, I'm pretty sure the problem lies with either:  

(a) something either missing or extra in my Dockerfile that is not documented
(b) the heroku backend

Something to note as well with the documentation.
1. Running ```heroku container:push``` does not work unless you specify both the app you intend to push as well as a process type. eg. ```heroku container:push web --app myapp```
2. Running ```heroku container:release web``` does not work unless you specify the app you intend to release. eg. ```heroku container:release web --app myapp```   

If this is related to the aforementioned problem, then it may lie with the heroku-cli since it will not allow me to follow the exact directions in the README.md of this repo, at least not on my system.

Heroku Info:
```
  $ heroku --version
  heroku/7.0.85 linux-x64 node-v8.9.1
```

Dockerfile:
```
FROM alpine:edge

MAINTAINER <support@collectiveacuity.com>

# Update Alpine environment
RUN echo '@edge http://nl.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories
RUN echo '@community http://nl.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories
RUN echo '@testing http://nl.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
RUN apk update
RUN apk upgrade
RUN apk add ca-certificates

# Install Python & Pip
RUN apk add curl
RUN apk add python3
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3

# Install C Compiler Dependencies
RUN apk add gcc
RUN apk add g++
RUN apk add python3-dev
RUN apk add postgresql-dev
RUN apk add libffi-dev

# Install Python Modules
RUN pip3 install flask
RUN pip3 install cffi
RUN pip3 install gunicorn
RUN pip3 install gevent
RUN pip3 install requests

# Clean APK cache
RUN rm -rf /var/cache/apk/*

ENV SYSTEM_ENVIRONMENT=prod
ENV SYSTEM_PLATFORM=heroku
ADD ./cred /opt/cred
ADD ./data /opt/data
ADD ./server /opt/server
CMD gunicorn -k gevent -w 1 --chdir /opt/server launch:app -b 0.0.0.0:$PORT
```

**Comment by dmathieu** [comment]
Hi,

You should look into your app logs to see why the app crashes. If your app logs an error to stdout, this will be displayed there.
This also can't be an issue with this CLI plugin, which doesn't handle running apps at all. Could you open a support ticket instead?
We will then be able to look into your app's code to better help you.

Thanks

**Comment by rj919** [comment]
Therein lies the problem... logging is turned on and when I build and run the container using docker on my machine there aren't any errors. But, when I go to the dashboard.heroku.com/apps/myapp/logs, I only get the following message:
```
2018-06-02T15:00:15.524239+00:00 heroku[web.1]: State changed from crashed to starting
2018-06-02T15:00:15.207601+00:00 app[api]: Deployed web (25aa0b708e93) by user support@collectiveacuity.com
2018-06-02T15:00:15.207601+00:00 app[api]: Release v11 created by user support@collectiveacuity.com
2018-06-02T15:00:24.948677+00:00 heroku[web.1]: State changed from starting to crashed
2018-06-02T15:00:24.950965+00:00 heroku[web.1]: State changed from crashed to starting
2018-06-02T15:00:30.799146+00:00 heroku[web.1]: State changed from starting to crashed
```
No errors are being logged... the app simply isn't starting at all to get to the point where it might log errors. I have tried to add -t 60 to see if it is timing out, but that isn't the problem. As I said in the previous post, the app starts normally and quickly on my own machine. There are no problems/errors reported running either ```heroku container:push web --app myapp``` or ```heroku container:release web --app myapp``` from the cli and in the dashboard activity it reports that it has been deployed.

On top of this, I have tried to deploy the app using a different CMD that uses python's own WSGI server and I have tried to deploy an app which did nothing other than print out a message... and I get the exact same error. There is literally no information that I can see other than that message.

I'll open a support ticket, but I'm not convinced yet that this isn't a issue with heroku-container-registry... since as I said, this problem only started after the recent update was pushed. I had no problem deploying the exact same apps before container:release.

**Comment by rj919** [comment]
After a bit of incrementalism, I discovered that the app fails whenever the "size" reported is above 7000 +/- ???.

I have been able to get the app to deploy with every configuration of dependencies but only as long as the build size is less than 7000. 
So, this deploys:
```
latest: digest: sha256:e086023238d733762dc1f6a5296dedded63a85bb187e0ad1f749a56533e3a487 size: 6827
```
but this crashes (with no other messages):
```
latest: digest: sha256:440abb869fa7a51b6e697fa828cdab604a4c9683c136287005a4eddf160f771a size: 7240
```

**Comment by dmathieu** [comment]
Ah, you've hit a known limitation of the platform then.
Images with more than 40 layers are likely not to start: https://devcenter.heroku.com/articles/container-registry-and-runtime#known-issues-and-limitations

**Comment by rj919** [comment]
Interesting... but in this case, the number of steps which were built in the latter image (size 7240) which crashed was only 37 and the number of layers which were pushed was 33. So, is there also a cap on 'size'?

On a related note, I'm not sure what 'size' refers to. The memory imprint of the image according to docker is 332MB (below the slug size limit).
