### ISSUE TITLE
Provide optional "release on push" functionality for Docker deployments

### ISSUE THREAD

**Issue by toedter** [heroku/heroku-container-registry#71]
I understand the benefits of separating the Docker registry push and the actual Heroku release. But in many use cases it is convenient if a release is done automatically directly after a successful push (This was the Heroku default before May 29th).

It would be great if you could provide a switch or option to enable this feature again.

Thanks

Kai

**Comment by dmathieu** [comment]
Thank you for the suggestion. I am passing it to our Product team.
The thing with releasing on push is actually that it fits only specific use cases where a single image is used for a single process type.
If you wish to use the same image for several process types, or if you're using [release phase](https://devcenter.heroku.com/articles/release-phase), releasing on push is more of a hassle as it creates a new release for each image being pushed.

There is a way you could stop worrying about pushing and releasing all together though.
Our build manifest feature will build, push and release your docker images for you: https://devcenter.heroku.com/articles/heroku-yml-build-manifest

**Comment by toedter** [comment]
Thx Damien. I my use case I am using Travis-CI to build the Docker image, push the same Docker image to different registries and deploy it to several cloud platforms, including Heroku. I use this mainly for demos at conferences to show how great Heroku is.
